name: build-and-push-image

on:
  pull_request:
    branches:
      - 'main'

env: 
  PROJECT_NAME: daemonset-installer
  # set TAG by the command "echo "::set-output name=sha_short::$(git rev-parse --short HEAD)""
  TAG: ${{ github.event.pull_request.head.sha_short }}
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./build/images
          file: ./build/images/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.PROJECT_NAME }}:${{ env.TAG }}